name: ner
channels:
  - anaconda
  - conda-forge
  - huggingface
  - pytorch
  - intel
  - defaults
dependencies:
  - python=3.8
  - numpy
  - tqdm
  - pytorch
  - transformers
  - pytorch-lightning
  - pip
  - pip:
      - datasets
      - torchmetrics
      - dvc
